image: python:3.11

docu:
  stage: build
  script:
  - python -V
  # install common requirements
  - pip install -r requirements.txt 
  # generate docu
  - cd docs
  - sphinx-apidoc -f -o source ../skcomm
  - sphinx-build -b html source ../public
  # make docu available for download via artefacts
  artifacts:
    paths:
    - public
  # generate docu only for master branch
  only:
  - master


unittests:
  stage: test
  script:
  - python -V
  - pip install -r requirements.txt 
  - python -m unittest discover -s skcomm/tests -t . -v
