image: python:3.7

docu:
  stage: docu
  script:
  - python -V
  - pip install -U sphinx
  - cd docs
  - sphinx-build -b html source ../public


unittests:
  stage: unittests
  script:
  - python -V
  - pip install -r requirements.txt 
  - cd comm/tests
  - python -m unittest