# To create a new conda environment for comm use the following command:
# conda env create --name <env-name> --file environment.yml
name: comm
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.1
  - myst-parser=0.17.0
  - numpy=1.22.2
  - python=3.10.2
  - pyvisa=1.11.3
  - pyvisa-py=0.5.2
  - scipy=1.8.0
  - sphinx=4.3.2