# To create a new conda environment for comm use the following command:
# conda env create --name <env-name> --file environment.yml
name: skcomm
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.7.1
  - myst-parser=1.0.0
  - numpy=1.24.2
  - python=3.11.2
  - PyVISA=1.13.0
  - PyVISA-py=0.6.3
  - scipy=1.10.1
  - Sphinx=6.1.3
  - screeninfo=0.8.1